class Constants
  STILL_ALIVE_CUTOFF = -3
  BEAR_CHILD_CUTOFF = 7

  SEX_ODDS = 1
  MUTATE_ODDS = 2
  MAX_MUTATIONS = 4

  MAX_NUM_CHARS = 120

  MAX_ALTERING_ATTEMPTS = 20
  MAX_WALK_ATTEMPTS = 20
end
